Repository ozontech/seq-db, pull requests merged in 2025-09, with the labels that each got.

#61 docs: add architecture docs
  docs/en/02-flags.md
  docs/en/12-architecture.md
  docs/en/internal/fractions.md
  docs/ru/02-flags.md
  docs/ru/internal/fractions.md
  frac/sealed.go
  fracmanager/fetcher.go
Labels: documentation

#110 docs: update benchmarks documentation
  docs/en/11-benchmarks.md
  docs/ru/11-benchmarks.md
Labels: documentation, benchmarks

#114 chore: add `fgprof` handler
  go.mod
  network/debugserver/debugserver.go
Labels: performance

#104 perf: use `bytes.Index` for substring search
  pattern/pattern.go
  pattern/pattern_test.go
  pattern/substring.go
  pattern/substring_test.go
Labels: benchmarks, performance

#143 docs: make navigation buttons in readme.md
  README.md
Labels: documentation
