Repository ozontech/seq-db, pull requests merged in 2025-08, with the labels that each got.

#78 chore(all): update benchmark link to English version
  README.md
Labels: documentation

#3 Async search: list method and a bunch of various improvements and fixes
  api/seqproxyapi/v1/seq_proxy_api.proto
  api/storeapi/store_api.proto
  cmd/seq-db/seq-db.go
  config/config.go
  fracmanager/async_searcher.go
  fracmanager/encoding.go
  fracmanager/encoding_test.go
  pkg/seqproxyapi/v1/mappings.go
  pkg/seqproxyapi/v1/marshaler.go
  pkg/seqproxyapi/v1/marshaler_test.go
  pkg/seqproxyapi/v1/seq_proxy_api.pb.go
  pkg/seqproxyapi/v1/seq_proxy_api.pb.gw.go
  pkg/seqproxyapi/v1/seq_proxy_api_vtproto.pb.go
  pkg/storeapi/store_api.pb.go
  pkg/storeapi/store_api.pb.gw.go
  pkg/storeapi/store_api_vtproto.pb.go
  proxy/search/async.go
  proxy/search/mock/store_api_client_mock.go
  proxyapi/grpc_async_search.go
  proxyapi/grpc_v1.go
  proxyapi/mock/grpc_v1.go
  seq/qpr.go
  storeapi/client.go
  storeapi/grpc_async_search.go
  tests/integration_tests/integration_test.go
Labels: epic/async-search

#60 feat: logs S3 offloading
  Makefile
  cmd/seq-db/seq-db.go
  config.example.yaml
  config/config.go
  frac/active.go
  frac/fraction.go
  frac/info.go
  frac/remote.go
  frac/sealed.go
  frac/sealed_loader.go
  fracmanager/config.go
  fracmanager/fetcher_test.go
  fracmanager/fracmanager.go
  fracmanager/fracmanager_test.go
  fracmanager/fraction_provider.go
  fracmanager/loader.go
  fracmanager/proxy_frac.go
  fracmanager/sealed_frac_cache_test.go
  fracmanager/sealer_test.go
  go.mod
  go.sum
  metric/store.go
  storage/io.go
  storage/s3/uploader.go
  storeapi/grpc_search.go
  storeapi/grpc_v1.go
  storeapi/grpc_v1_test.go
  storeapi/store.go
  tests/setup/env.go
  util/fs.go
Labels: epic/s3-offloading
